
const userentityJson = {
  Id:"Id?",
  userName : "userName?",
  communityId: "communityId?",
  userType : "userType?",
  userDetails: "userDetails?",
  userEmail: "userEmail?",
  userImage: "userImage?",
  isActive: "isActive?",
  lastLogonDateTime: "lastLogonDateTime?",
  userAdditionalDetails : "userAdditionalDetails?",
  liveContentUsers: "liveContentUsers?",
  userMeetingProviders: "userMeetingProviders?",
  groupUsers: "groupUsers?",
  enrolledMeetings: "enrolledMeetings?",
  lessonDataReviews: "lessonDataReviews?",
  lessonDataUsers: "lessonDataUsers?",
  community: "community?",
  liveContents: "liveContents?",
  //SocketId: "SocketId?",
  CommunityUrl: "CommunityUrl?",
  externalUserId: "externalUserId?",
  externalTenantUserId: "externalTenantUserId?",
  externalTenantUserAppId:"externalTenantUserAppId?",
  channelUsers: "channelUsers?",
  sectionReviews: "sectionReviews?",
  payments: "payments?"
    
};

const userdtoJson = {
  Id:"Id?",
  userName : "userName?",
  communityId: "communityId?",
  userType : "userType?",
  userDetails: "userDetails?",
  userEmail: "userEmail?",
  userImage: "userImage?",
  isActive: "isActive?",
  lastLogonDateTime: "lastLogonDateTime?",
  userAdditionalDetails : "userAdditionalDetails?",
  liveContentUsers: "liveContentUsers?",
  userMeetingProviders: "userMeetingProviders?",
  groupUsers: "groupUsers?",
  enrolledMeetings: "enrolledMeetings?",
  lessonDataReviews: "lessonDataReviews?",
  lessonDataUsers: "lessonDataUsers?",
  community: "community?",
  liveContents: "liveContents?",
  //SocketId: "SocketId?",
  CommunityUrl: "CommunityUrl?",
  externalUserId: "externalUserId?",
  externalTenantUserId: "externalTenantUserId?",
  externalTenantUserAppId:"externalTenantUserAppId?",
  channelUsers: "channelUsers?",
  sectionReviews: "sectionReviews?",
  payments: "payments?"
};

const userentityToDtoJson = {
  Id:"Id?",
  userName : "userName?",
  communityId: "communityId?",
  userType : "userType?",
  userDetails: "userDetails?",
  userEmail: "userEmail?",
  userImage: "userImage?",
  isActive: "isActive?",
  lastLogonDateTime: "lastLogonDateTime?",
  userAdditionalDetails : "userAdditionalDetails?",
  liveContentUsers: "liveContentUsers?",
  userMeetingProviders: "userMeetingProviders?",
  groupUsers: "groupUsers?",
  enrolledMeetings: "enrolledMeetings?",
  lessonDataReviews: "lessonDataReviews?",
  lessonDataUsers: "lessonDataUsers?",
  community: "community?",
  liveContents: "liveContents?",
  //SocketId: "SocketId?",
  CommunityUrl: "CommunityUrl?",
  externalUserId: "externalUserId?",
  externalTenantUserId: "externalTenantUserId?",
  externalTenantUserAppId:"externalTenantUserAppId?",
  channelUsers: "channelUsers?",
  sectionReviews: "sectionReviews?",
  payments: "payments?"
};

const userdtoToEntityJson = {
  Id:"Id?",
  userName : "userName?",
  communityId: "communityId?",
  userType : "userType?",
  userDetails: "userDetails?",
  userEmail: "userEmail?",
  userImage: "userImage?",
  isActive: "isActive?",
  lastLogonDateTime: "lastLogonDateTime?",
  userAdditionalDetails : "userAdditionalDetails?",
  liveContentUsers: "liveContentUsers?",
  userMeetingProviders: "userMeetingProviders?",
  groupUsers: "groupUsers?",
  enrolledMeetings: "enrolledMeetings?",
  lessonDataReviews: "lessonDataReviews?",
  lessonDataUsers: "lessonDataUsers?",
  community: "community?",
  liveContents: "liveContents?",
  //SocketId: "SocketId?",
  CommunityUrl: "CommunityUrl?",
  externalUserId: "externalUserId?",
  externalTenantUserId: "externalTenantUserId?",
  externalTenantUserAppId:"externalTenantUserAppId?",
  channelUsers: "channelUsers?",
  sectionReviews: "sectionReviews?",
  payments: "payments?"
};

module.exports.userentityJson = userentityJson;
module.exports.userdtoJson = userdtoJson;
module.exports.userentityToDtoJson = userentityToDtoJson;
module.exports.userdtoToEntityJson = userdtoToEntityJson;